### ISSUE TITLE
how to inference for edges to faces

### ISSUE THREAD

**Issue by BrewieRain** [inventwithdean/Pix2PixHD#2]
Thank you for your awesome work!I want to ask how to inference?Can you provide the pre-trained model?Thanks!

**Comment by inventwithdean** [comment]
Yes, I will update the repository with pretrained models in about a week.

**Comment by BrewieRain** [comment]
Thank you!I have another question, can your model generate a real face based on this contour map?Can you show me the result?Thank you so much!
![hq_contour](https://github.com/user-attachments/assets/61a21101-7ebb-419e-953a-ee1277545c94)

**Comment by inventwithdean** [comment]
I think if we use the CelebaMask's manipulated segmentation maps instead of edges to train the network, then yes this contour can be converted into real face. But currently, this edge to face model can't achieve that.
